name: Keep Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check IST time (skip 12:31 AM - 5:29 AM)
        run: |
          HOUR=$(TZ='Asia/Kolkata' date +%H)
          MINUTE=$(TZ='Asia/Kolkata' date +%M)
          if [ "$HOUR" -eq 0 ] && [ "$MINUTE" -gt 30 ]; then
            echo "SLEEP_TIME=true" >> $GITHUB_ENV
          elif [ "$HOUR" -gt 0 ] && [ "$HOUR" -lt 5 ]; then
            echo "SLEEP_TIME=true" >> $GITHUB_ENV
          elif [ "$HOUR" -eq 5 ] && [ "$MINUTE" -lt 30 ]; then
            echo "SLEEP_TIME=true" >> $GITHUB_ENV
          else
            echo "SLEEP_TIME=false" >> $GITHUB_ENV
          fi

      - name: Ping Render backend
        if: env.SLEEP_TIME == 'false'
        run: curl -s -o /dev/null -w "%{http_code}" https://imagemanagement-dku8.onrender.com/health
